# Generated by Django 5.2.7 on 2025-10-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['title'], 'verbose_name': 'CAR', 'verbose_name_plural': 'CARS'},
        ),
    ]
