# Generated by Django 5.2.7 on 2025-10-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0002_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartype',
            options={'ordering': ['title'], 'verbose_name': 'CARtype', 'verbose_name_plural': 'CARtypes'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['title'], 'verbose_name': 'COUNTRY', 'verbose_name_plural': 'COUNTRIES'},
        ),
    ]
